[theme]
primaryColor = "#7B48EA"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F1EDFB"
textColor = "#29184E"
font = "sans serif"
[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
